### ISSUE TITLE
feat: assert download

### ISSUE THREAD

**Issue by lucky9-cyou** [H-Freax/ThinkGrasp#1]
Thank you for your excellent project.

Could you please provide a download link for a compressed file? When downloading through Google Drive, it automatically compresses the file, but it often fails.
![CleanShot 2024-09-12 at 20 33 54@2x](https://github.com/user-attachments/assets/f6f0f696-bb99-4b84-a059-3772c58b0d53)

**Comment by lucky9-cyou** [comment]
I would like to ask about the location of the file `test.py`.

**Comment by H-Freax** [comment]
Thanks for the issue!
Just upload it here https://huggingface.co/datasets/FreaxRuby/Thinkgrasp/tree/main 
Hope it helps!

Because it is zero-shot, the simulation Python file is the "test" because we don't need to train.
