### ISSUE TITLE
where can I get the urdf of workspace？

### ISSUE THREAD

**Issue by nolann030628** [H-Freax/ThinkGrasp#2]

**Comment by H-Freax** [comment]
You can download it here: https://huggingface.co/datasets/FreaxRuby/Thinkgrasp/tree/main 
You can also use the assets mentioned in the readme.

**Comment by nolann030628** [comment]
Thank you very much for your response！

**Comment by nolann030628** [comment]
sorry I am still confused cuz I can only find simplified objects and unseen objects in the assets and didin't find the file realted to workspace. Would you please specify the path of the workspace.urdf?

**Comment by H-Freax** [comment]
https://github.com/xukechun/Vision-Language-Grasping You can find here :)
