### ISSUE TITLE
找不到langsam.txt

### ISSUE THREAD

**Issue by green-cpu** [H-Freax/ThinkGrasp#4]
您好，感谢您出色的工作。
在配置环境的步骤中.我按照您提供的方法pip install langsam.txt发生了报错，想请教您如何进行解决呢？谢谢！

**Comment by H-Freax** [comment]
langsam.txt的内容如下


requests
ray[all]
transformers
openai
git+https://github.com/IDEA-Research/GroundingDINO.git
git+https://github.com/facebookresearch/segment-anything.git
