### ISSUE TITLE
simplified models

### ISSUE THREAD

**Issue by laynewong** [H-Freax/ThinkGrasp#5]
请问您是如何简化graspnet里面的3D models？ 我曾经简化过这些模型然后放到Gazebo中，但是会出现滑动现象。我看到您为它们编写的URDF文件，visual和collision两部分使用了不同的obj文件。您是如何简化它们的呢，您能够提供简化模型相关的代码吗，谢谢！

**Comment by H-Freax** [comment]
相关的部分我是直接用的https://github.com/xukechun/Vision-Language-Grasping 的code 可以在那里提一下issue试试看

**Comment by laynewong** [comment]
> 相关的部分我是直接用的https://github.com/xukechun/Vision-Language-Grasping 的code 可以在那里提一下issue试试看

好的，非常感谢您的回复！
